global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'catalog_service'
    static_configs:
      - targets: ['catalog_service:8000']

  - job_name: 'orders_service'
    static_configs:
      - targets: ['orders_service:8000']

  - job_name: 'users_service'
    static_configs:
      - targets: ['users_service:8000']

  - job_name: 'reviews_service'
    static_configs:
      - targets: ['reviews_service:8000']

  - job_name: 'celery'
    static_configs:
      - targets: ['celery_exporter:9540']

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
